### ISSUE TITLE
request for clarification about test data

### ISSUE THREAD

**Issue by omry** [orenbenkiki/yamlreference#8]
I am confused:
it looks like there are files with different names contain identical data, for example b-as-line-feed and b-as-space, yet you expect different outputs for them.
Can you clarify this?
```
$ ls -1  b-as-line-feed.input  b-as-space.input  | xargs -i  hexdump  {}
0000000 000a                                   
0000001
0000000 000a                                   
0000001
$ diff   b-as-line-feed.output  b-as-space.output 
2c2
< L\x0a
---
> l\x0a
```

**Comment by orenbenkiki** [comment]
Test data describes what happens if, during parsing, some production **X** is attempted when the remaining unparsed input data contains some character(s) **Y**.

Thus, the test files are named **X**._something_.**input**, which contains the input character(s) **Y**; and **X**._something_.**output**, which contains the expected result **Z**.

It is to be expected that applying two different parsing productions **X1** and **X2** to the same input **Y** will result in different output **Z1** and **Z2**; for example, a space may be part of the indentation in a block node, or a separator between flow nodes, or actual content of a scalar node, depending on the state of the parser when it reaches the space character - three very different outcomes to parsing the same ASCII space character.

If you want to examine the results of full parsing of some data, try: http://ben-kiki.org/ypaste

**Comment by omry** [comment]
thanks for clarifying.
